name: Management-Web

services:

  dns:
    image: ubuntu/bind9:latest
    container_name: dns
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./conf/bind9/named.conf.options:/etc/bind/named.conf.options
      - ./conf/bind9/named.conf.local:/etc/bind/named.conf.local
      - ./conf/bind9/db.insrv5.net:/etc/bind/db.insrv5.net
      - ./conf/bind9/db.insrv5.local:/etc/bind/db.insrv5.local
      - ./log/dns:/var/log/bind9
    networks:
      insrv_net:
        ipv4_address: 192.168.5.253
      insrv_local:
        ipv4_address: 192.168.51.253

  openldap:
    image: osixia/openldap:latest
    container_name: ldap-server
    command: --copy-service
    environment:
      - LDAP_ORGANISATION=Internal SL
      - LDAP_DOMAIN=insrv5.local
      - LDAP_ADMIN_PASSWORD=admnpasswd
      # --- LDAP Secure (SSL/TLS)---
      - LDAP_TLS=true
      - LDAP_TLS_VERIFY_CLIENT=try
      - LDAP_TLS_CRT_FILENAME=insrv5.net.crt
      - LDAP_TLS_KEY_FILENAME=insrv5.net.key
      - LDAP_TLS_CA_CRT_FILENAME=insrv5.net.crt
    volumes:
      - ldap_data:/var/lib/ldap
      - ./conf/ssl/certs:/container/service/slapd/assets/certs/
    depends_on:
      - dns
    dns:
      - 192.168.51.253
    networks:
      insrv_local:
        ipv4_address: 192.168.51.252

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-admin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_SERVER_NAME=Internal5 LDAP
    depends_on:
      - openldap
    networks:
      insrv_local:
        ipv4_address: 192.168.51.4

  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root # Esto en prod. debería ir en un .env
      - MYSQL_DATABASE=insrv5_db # Esto en prod. debería ir en un .env
      - MYSQL_USER=user # Esto en prod. debería ir en un .env
      - MYSQL_PASSWORD=1234 # Esto en prod. debería ir en un .env
    volumes:
      - db_data:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    networks:
      insrv_local:
        ipv4_address: 192.168.51.250
    
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=user # Esto en prod. debería ir en un .env
      - PMA_PASSWORD=1234 # Esto en prod. debería ir en un .env
    depends_on:
      - db
    networks:
      insrv_local:
        ipv4_address: 192.168.51.3
    
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf/nginx/insrv5.net.conf:/etc/nginx/conf.d/default.conf
      - ./conf/ssl/certs/insrv5.net.crt:/etc/ssl/certs/insrv5.net.crt
      - ./conf/ssl/certs/insrv5.net.key:/etc/ssl/certs/insrv5.net.key
      - ./log/nginx:/var/log/nginx
    networks:
      insrv_net:
        ipv4_address: 192.168.5.10
        
  apache:
    build:
      context: ./Docker/apache
    container_name: apache
    volumes:
      - ./conf/www:/var/www/html/
      - ./log/apache:/var/log/apache2
    networks:
      insrv_net:
        ipv4_address: 192.168.5.2
      insrv_local:
        ipv4_address: 192.168.51.2

volumes:
  db_data:
  ldap_data:

networks:
  insrv_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24
  insrv_local:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.51.0/24