auth_request /auth-check;

error_page 401 = https://insrv5.net/users/index.php?return=$scheme://$host$request_uri;
error_page 403 = /error403;
error_page 404 = /error404;

location = /auth-check {
    internal;

    proxy_pass http://192.168.51.2/users/auth_check.php?req_role=$req_role;
    
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-URI $request_uri;
    proxy_set_header Cookie $http_cookie;
}

location = /sso {
	auth_request off;
	
	proxy_pass http://192.168.51.2/users/sso.php$is_args$args;

	proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

}

location = /logout {
    auth_request off;
    
    proxy_pass http://192.168.51.2/users/logout.php$is_args$args;
    
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

location = /error403 {
	internal;
	auth_request off;
    proxy_pass http://192.168.51.2/errors/403.html;
}

location = /error404 {
	internal;
	auth_request off;
    proxy_pass http://192.168.51.2/errors/404.html;
}