server {
	listen 443 ssl http2;

	ssl_certificate /etc/ssl/certs/insrv5.net.crt;
	ssl_certificate_key /etc/ssl/certs/insrv5.net.key;

	error_log /var/log/nginx/insrv5_error.log debug;
    access_log /var/log/nginx/insrv5_access.log;

	server_name insrv5.net;

	location / {
		proxy_pass http://192.168.5.2;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
